language:
  - python

python: 
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then pip install pytest-cov python-coveralls;
    else pip ins 
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then py.test -vv script.py --cov script.py;
    else py.test -vv script.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then coveralls;
    fi

notifications:
  email: false
